### ISSUE TITLE
add_meeting_registrant results in RegistrantConfirmation error

### ISSUE THREAD

**Issue by gpe5280** [licht1stein/pyzoom#148]
From the command line:

```python
$ python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyzoom import ZoomClient
>>> client = ZoomClient(ZM_KEY, ZM_SECRET)
>>> client.meetings.add_meeting_registrant(XXXXXXX, first_name='John', last_name='Public', email='boss@example.com', job_title='Boss')
```
The following error occurs, however, the registrant **is added** to the meeting roster.

```stdout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/websites/domains/stoicagilist.com/system/lib/python3.10/site-packages/pyzoom/_client.py", line 121, in add_meeting_registrant
    return schemas.RegistrantConfirmation(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RegistrantConfirmation
join_url
  field required (type=value_error.missing)
```
I tried adding the join url to the parameter list (`join_url='https://us02web.zoom.us/j/XXXX?pwd=XXXX'`), since it is different from the registration url, but the result was the same.

(PS. Thank you for this excellent library. It has saved me hours of coding!)

**Comment by licht1stein** [comment]
Please make a PR with the fix!
